### ISSUE TITLE
Saving state to a file causes segfault setting a tooltip image

### ISSUE THREAD

**Issue by bmenrigh** [punesemu/puNES#137]
Saving states works just fine when I save to one of the existing 0-9 states. When I try to save the state to a file though I get a segfault:

From GDB:
```
Thread 1 "punes" received signal SIGSEGV, Segmentation fault.
0x00007ffff7a10085 in QAction::setToolTip(QString const&) () from /usr/lib64/libQt5Widgets.so.5
(gdb) bt
#0  0x00007ffff7a10085 in QAction::setToolTip(QString const&) () at /usr/lib64/libQt5Widgets.so.5
#1  0x0000555555744687 in mainWindow::set_save_slot_tooltip(unsigned char, char*)
    (this=0x555555b599b0, slot=slot@entry=10 '\n', buffer=buffer@entry=0x555556c22490 "") at mainWindow.cpp:616
#2  0x000055555571ed23 in gui_set_save_slot_tooltip(BYTE, char*) (slot=slot@entry=10 '\n', buffer=buffer@entry=0x555556c22490 "")
    at qt.cpp:239
#3  0x00005555555c0144 in preview_image (sb=0x5555559a09e0 <screen+32>, slot=10 '\n') at save_slot.c:783
#4  save_slot_element_struct
    (mode=mode@entry=0 '\000', slot=slot@entry=10 '\n', src=<optimized out>, size=size@entry=122880, fp=fp@entry=0x555556b3c000, preview=preview@entry=1 '\001') at save_slot.c:210
#5  0x00005555555c2ad2 in save_slot_operation (mode=<optimized out>, 
    mode@entry=0 '\000', slot=slot@entry=10 '\n', fp=fp@entry=0x555556b3c000) at save_slot.c:772
#6  0x00005555555c3fb2 in save_slot_save (slot=slot@entry=10 '\n') at save_slot.c:73
#7  0x0000555555742260 in mainWindow::s_state_save_file() (this=<optimized out>) at mainWindow.cpp:1427
```

I think the issue is that there are 10 save slots in the GUI, labeled 0 through 9. When saving to a file the slot get set to 10 and some code is called to set the tooltip PNG image for slot 10.

It seems like there needs to be some additional check so when saving a state to a file it doesn't try to update the GUI tooltip with the preview image.

**Comment by punesemu** [comment]
https://github.com/punesemu/puNES/commit/544ed12446d4dfe5f4c2f126b37c7b5e2d9087e8. Thanks so much for the contribution Brandon.
